# Generated by Django 4.0.6 on 2022-08-15 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fetch_Meta_Data_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='userfiles',
            name='metadata',
        ),
        migrations.AddField(
            model_name='metadata',
            name='file_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userfiles',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
